version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.template.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_blue
      - app_green

  app_blue:
    image: ${BLUE_IMAGE}
    environment:
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=${PORT}
      - APP_POOL=blue
    ports:
      - "8081:3000"

  app_green:
    image: ${GREEN_IMAGE}
    environment:
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=${PORT}
      - APP_POOL=green
    ports:
      - "8082:3000"
